### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by jorgegonzalez** [jorgegonzalez/zoe#1]
Investigate ways to speed up the CLI. ESLint cache is possibly not being set.

**Comment by azdanov** [comment]
Maybe [standard-engine](https://github.com/standard/standard-engine) from `standard style` could be used either as an inspiration or directly.

In `xo` [cache](https://github.com/xojs/xo/blob/master/lib/options-manager.js#L34) is set [here](https://github.com/xojs/xo/blob/71d06a0849711946221106bd1748a6485c2968fa/index.js#L36). But it seems there shouldn't be a problem here.

**Comment by jorgegonzalez** [comment]
If you look through the commit history, I dropped `standard-engine` (and basically forked it) because it doesn't let you configure `rules`.

Thanks for confirming that the cache is working

**Comment by jorgegonzalez** [comment]
Going to close this for now.
