### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by azdanov** [jorgegonzalez/zoe#10]
Writing more tests would be beneficial in reducing _code rot_ for future features and/or updates.

**Comment by jorgegonzalez** [comment]
I'll merge anyone wants to write.

**Comment by azdanov** [comment]
There should be an integration test suite to test on each build, `ts -> js`, on Travis. 

Should check, on a predefined codebase, that has already known errors, both linting and fixing. Maybe other options as well, to be sure nothing is broken between builds.

**Comment by jorgegonzalez** [comment]
> There should be an integration test suite to test on each build, `ts -> js`, on Travis.

How do we go about testing this?

I mentioned previously that I'm bad at writing (good) tests, and I'd love some help from you to improve this skill.

**Comment by azdanov** [comment]
@jorgegonzalez I'll have a look. Never tried something like this before.

Probably will need some code generator to output dummy files. Run transpiled code on them and compare the results.

**Comment by azdanov** [comment]
I've noticed several issues after implementing integration test and running on `1.9.1`.

* Passing path to zoe now needs globbing, e.g /Users/projects/zoe/**
* Flow seems to be having problems with my example snippet, it throws `Unexpected token export`

Test was working fine on `1.8.4`.

Apart from bug concerning paths. Where it would remove all other file paths, except `.js`.
https://github.com/jorgegonzalez/zoe/blob/588abd12ed02d9cb8da87974130b36daab4f0aaf/src/engine.ts#L80

**Comment by jorgegonzalez** [comment]
I was messing around with a different architecture. Was a bad idea. Give me at least until tomorrow, trying to bundle the app at the moment.

**Comment by jorgegonzalez** [comment]
I'm filtering out non `.js` paths because `.ts` files are being handled by a separate `CLIEngine` instance (`babel-eslint => "*.js"`, `typescript-eslint-parser => "*.ts"`). Is there a bug that you're noticing with this?

**Comment by jorgegonzalez** [comment]
Travis is still failing on occasion.

**Comment by jorgegonzalez** [comment]
Oh it's because I bumped up the version (I think?) ... My bad

**Comment by azdanov** [comment]
Will do something about this tomorrow. Updating snapshots on each version bump is annoying.

**Comment by jorgegonzalez** [comment]
I think we can close this now as you have done a fantastic job of setting up a good testing foundation.
