### ISSUE TITLE
Init option

### ISSUE THREAD

**Issue by azdanov** [jorgegonzalez/zoe#12]
An easier way to bootstrap a new project with `--init`. 

CLI can ask where to put the config, either in `package.json`, `.zoerc`, etc.. and the config file itself can contain some example rules that are on by the default?

**Comment by jorgegonzalez** [comment]
Yeah that's a good idea. I also think running `zoe --init` in a new project should download and add `zoe` to the project's `devDependencies`, and add a `lint` command to `package.json#script`:

```json
"scripts": {
  "lint": "zoe",
  "format": "zoe --fix"
}
```

`xo` does this as well.

**Comment by jorgegonzalez** [comment]
https://github.com/xojs/xo-init/blob/master/index.js

This is how `xo` does it.

**Comment by jorgegonzalez** [comment]
Working on this now.

**Comment by jorgegonzalez** [comment]
Wrote a basic test: https://github.com/jorgegonzalez/zoe/blob/master/test/init.spec.ts

How can it be improved? It takes forever to run as it executes `npm install` in a new directory.

**Comment by jorgegonzalez** [comment]
I will add a prompt with [`inquirer`](https://github.com/SBoudrias/Inquirer.js) to ask where the Zoe config should be created, and then I will consider this issue closed.
