### ISSUE TITLE
Implement "add" command

### ISSUE THREAD

**Issue by jorgegonzalez** [jorgegonzalez/zoe#15]
After sharing this project with a few people, one of the main impressions I've gotten is issues with the preset (`airbnb` specifically).

I want to implement an `add` command and option that will download an `eslint-config` and its associated dependencies, and then reconfigure the config based on that.

```sh
zoe add [xo|standard|google|facebook|other]

# Downloads eslint-config-{preset} and its peerdeps
# Creates a .zoerc file that extends: [{preset}]
```

**Comment by azdanov** [comment]
I've used [install-peerdeps](https://github.com/nathanhleung/install-peerdeps) cli tool for airbnb before. Could be useful.

**Comment by jorgegonzalez** [comment]
I was looking at that too

**Comment by jorgegonzalez** [comment]
Not sure if I want to implement this anymore.
