### ISSUE TITLE
Create Zoe website

### ISSUE THREAD

**Issue by jorgegonzalez** [jorgegonzalez/zoe#17]
Create a simple website for Zoe, to be deployed on Netlify. I'm probably going to use Gatsby.

**Comment by azdanov** [comment]
I'm building a personal website at the moment with Gatsby also. Can help out.

Also consider a custom __free__ domain from [js.org](https://js.org/), something like `https://zoe.js.org`. They also support Netlify.

**Comment by jorgegonzalez** [comment]
https://github.com/js-org/js.org/pull/2158

**Comment by jorgegonzalez** [comment]
zoe.js.org is live.

**Comment by jorgegonzalez** [comment]
Will probably use [Docusaurus](https://docusaurus.io/) as I've been meaning to try it out for some time.

**Comment by azdanov** [comment]
[gatsby-starter-docs](https://github.com/ericwindmill/gatsby-starter-docs) looks like a nice alternative.

Although Docusaurus seems easier to use.

**Comment by jorgegonzalez** [comment]
That works

**Comment by jorgegonzalez** [comment]
Docusaurus has way more features features out of the box. That Gatsby starter is pretty bare-bones and I don't want to spend too much time working on the site. I love Gatsby (using it for my own portfolio), but I think Docusaurus is the better solution for now.

**Comment by jorgegonzalez** [comment]
Nevermind going with Gatsby

**Comment by azdanov** [comment]
I'd start from scratch and use the starter as a reference. It has a lot of not needed plugins.

**Comment by jorgegonzalez** [comment]
What is some actual content we can put on the site now?

**Comment by jorgegonzalez** [comment]
Besides a straight copy-paste from the README? Maybe extract sections of the README into their own pages?

**Comment by jorgegonzalez** [comment]
I don't want to have to update both the README and a `docs/` page every time there's a change.

**Comment by azdanov** [comment]
I like what https://necolas.github.io/normalize.css/ does. 
A prettier way to view the readme, and some docs.

Readme should have general information. `docs/` something more in depth.

For now a placeholder will suffice, just to kick off.

Later one some fancy stuff could be added.

**Comment by azdanov** [comment]
Could also use typescript for the website.

**Comment by jorgegonzalez** [comment]
> Could also use typescript for the website.

Why not

**Comment by jorgegonzalez** [comment]
I'm wondering if we should move the website to a different repository.

**Comment by azdanov** [comment]
Good idea, keeping the project clean. But will have reassign `zoe.js.org` to the new repo.

**Comment by azdanov** [comment]
Can this be closed now?
