### ISSUE TITLE
CI on Windows

### ISSUE THREAD

**Issue by azdanov** [jorgegonzalez/zoe#25]
Should test build on Windows. Possibly via [AppVeyor](https://www.appveyor.com/).

**Comment by jorgegonzalez** [comment]
Setting this up now.

**Comment by jorgegonzalez** [comment]
Will look into this more later actually.

**Comment by jorgegonzalez** [comment]
This should be set up now. We just need passing tests.

**Comment by jorgegonzalez** [comment]
I believe this issue is done yes?
