### ISSUE TITLE
Automated Semantic Release

### ISSUE THREAD

**Issue by azdanov** [jorgegonzalez/zoe#26]
Consider using [semantic-release](https://github.com/semantic-release/semantic-release) package.

I'm trying it out on my personal website project and liking it thus far. Also it can create automatic release notes and change-log via plugins.

The only problem is how to integrate it to an already rolling project.

**Comment by jorgegonzalez** [comment]
Seems cool, I'll look into it when I have more time.

**Comment by jorgegonzalez** [comment]
Do you have access to create a project on this repo? https://github.com/jorgegonzalez/zoe/projects

**Comment by azdanov** [comment]
@jorgegonzalez Yep, think so.

**Comment by jorgegonzalez** [comment]
Can you go ahead and make a project for all maintenance-related goals? Automated semantic release, set up AppVeyor, set up zoe.js.org, etc.

**Comment by jorgegonzalez** [comment]
I looked through the Semantic release docs and I think it’s a great idea.

**Comment by jorgegonzalez** [comment]
Can you help me set this up? Seems complicated.

**Comment by azdanov** [comment]
Sure can!

**Comment by jorgegonzalez** [comment]
Will look into this again when I have more time. I tried the CLI but it is having issues with npm's 2FA 

https://github.com/semantic-release/cli/issues/213

**Comment by azdanov** [comment]
https://github.com/azdanov/azdanov.github.io/blob/936205e39be5a1a2ef89e01c6a8a9973ef403441/package.json#L109

That line should probably be `master`, since I have a different workflow in my repo.

**Comment by jorgegonzalez** [comment]
> Note: Only the auth-only level of npm two-factor authentication is supported, semantic-release will not work with the default auth-and-writes level.

Not sure how I feel about this

**Comment by jorgegonzalez** [comment]
I think I'm going to use the git and github plugins, but I'll continue manually publishing to npm. I'm not willing to turn off 2FA for publishing.

**Comment by jorgegonzalez** [comment]
I got it working on CircleCI

**Comment by jorgegonzalez** [comment]
Can we bump `package.json#version` in the release commit, without actually publishing?

**Comment by jorgegonzalez** [comment]
Looks like the `prepare` object does it. Hoping it works.

**Comment by jorgegonzalez** [comment]
We need to figure out a way to update the snapshot that includes `Zoe <version>` every time we bump it.

**Comment by jorgegonzalez** [comment]
> Shouldn't have a need to do this. Is this to catch up with current version?

Yes. Currently `semantic-release` will publish, for example, `2.0.0` to GitHub, but `package.json#version` will stay at `1.9.0`. I then run `npm publish` which will bump `package.json#version`, and I have to commit and push that manually. 

> Or completely remove showing version number explicitly.

This seems like the easiest choice, but I really like having the version on every run

**Comment by azdanov** [comment]
> Yes. Currently semantic-release will publish, for example, 2.0.0 to GitHub, but package.json#version will stay at 1.9.0. I then run npm publish which will bump package.json#version, and I have to commit and push that manually.

You have to run `npm publish` manually because of issues with 2FA? I'm sure there is a way.

> This seems like the easiest choice, but I really like having the version on every run

Snapshots will have to be updated manually, since they imply human confirmation. Can't automate that, or it could introduce errors. 

For example if displaying version gets bugged and print out `Zoe [object Object]` instead of `Zoe 1.9.6`, then it will pass. Don't want that to happen.

**Comment by jorgegonzalez** [comment]
> You have to run npm publish manually because of issues with 2FA? I'm sure there is a way.

Yeah, you can input a one time password on a CI.
