### ISSUE TITLE
Experiment: Create bundle

### ISSUE THREAD

**Issue by jorgegonzalez** [jorgegonzalez/zoe#27]
I want to see it if it possible to bundle Zoe into a single bundle, including all non-imported dependencies. I attempted to do this earlier with no luck. The goal is to reduce the install size (i.e. since all dependencies should be included in the bundle, nothing but the bundle is installed during an `npm install`; `package.json#dependencies` will be modified after the build to be empty).

Yarn does a similar thing:

https://github.com/yarnpkg/yarn/blob/master/scripts/build-dist.sh
https://github.com/yarnpkg/yarn/blob/master/scripts/build-webpack.js

I think this plugin is the best way to accomplish this, though I'm not too familiar with Webpack:

https://webpack.js.org/plugins/dll-plugin/

update: We decided to go with Parcel instead.

**Comment by jorgegonzalez** [comment]
This may ultimately not work as some modules just don't work with Webpack.

**Comment by jorgegonzalez** [comment]
It might be worth it to try Parcel as well.

**Comment by azdanov** [comment]
Will update webpack branch, and create a branch with prettier to see which one suits zoe better.

**Comment by azdanov** [comment]
Here's the webpack config that worked (for reference).

<details>

<summary>webpack.config.js</summary>

```js
const path = require('path');
const webpack = require('webpack');
const pkg = require('./package.json');

module.exports = {
  mode: 'production',
  entry: './cli.ts',
  output: {
    filename: pkg.bin.zoe,
    path: __dirname,
    libraryTarget: 'commonjs2'
  },
  context: path.resolve(__dirname, 'src'),
  target: 'node',
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/
      }
    ]
  },
  resolve: {
    extensions: ['.ts', '.js', '.json']
  },
  externals: {
    meow: 'meow',
    eslint: 'eslint',
    'update-notifier': 'update-notifier'
  },
  plugins: [
    new webpack.DllReferencePlugin({
      manifest: require('./dist/vendor-manifest.json')
    }),
    new webpack.BannerPlugin({
      banner: '#!/usr/bin/env node',
      raw: true,
      entryOnly: true
    })
  ]
};
```

</details>

<details>

<summary>webpack.vendor.config.js</summary>

```js
const path = require('path');
const webpack = require('webpack');

module.exports = {
  mode: 'production',
  context: process.cwd(),
  target: 'node',
  resolve: {
    extensions: ['.js', '.json', '.ts']
  },
  entry: {
    vendor: [
      'v8-compile-cache',
      'chalk',
      'toml',
      'which-pm',
      'execa',
      'ora',
      'cosmiconfig',
      'deglob',
      'pify',
      'deepmerge'
    ]
  },
  output: {
    filename: '[name].dll.js',
    path: path.join(__dirname, 'dist'),
    library: '[name]_[hash]'
  },
  plugins: [
    new webpack.DllPlugin({
      path: path.join(__dirname, 'dist', '[name]-manifest.json'),
      name: '[name]_[hash]'
    })
  ]
};
```

</details>

**Comment by azdanov** [comment]
Parcel might be a better option. [feature/parcel](https://github.com/jorgegonzalez/zoe/tree/feature/parcel).

**Comment by jorgegonzalez** [comment]
https://spectrum.chat/?t=f348652f-1856-4348-9075-890acd8cb998

**Comment by azdanov** [comment]
What would bundling npm dependencies accomplish? 

Is it possible to bundle a dependency and exclude it from `package.json` when publishing to npm? So when a user does `npm install` there is one less dependency to download.

**Comment by jorgegonzalez** [comment]
> Is it possible to bundle a dependency and exclude it from package.json when publishing to npm?

This is the goal, and it’s what Yarn does and what npm is currently trying to do.

**Comment by azdanov** [comment]
> This is the goal, and it’s what Yarn does and what npm is currently trying to do.

Could you provide more information about this? I didn't know Yarn did something like that.

**Comment by jorgegonzalez** [comment]
[`yarn.js`](https://github.com/yarnpkg/yarn/blob/master/bin/yarn.js) is the entry point. 

[`build-dist.sh`](https://github.com/yarnpkg/yarn/blob/master/scripts/build-dist.sh) script builds the app with [this](https://github.com/yarnpkg/yarn/blob/master/scripts/build-webpack.js) Webpack Config.

Starting on [this[(https://github.com/yarnpkg/yarn/blob/master/scripts/build-dist.sh#L35) line, the relevant files are copied to the to-be-published directory, and they also copy [`v8-compile-cache`](https://github.com/yarnpkg/yarn/blob/master/scripts/build-dist.sh#L44).

[`update-dist-manifest.js`](https://github.com/yarnpkg/yarn/blob/master/scripts/update-dist-manifest.js) deletes the now-bundled dependencies.

Do a `yarn add yarn` somewhere to see what that looks like.

**Comment by jorgegonzalez** [comment]
`npm/cli` is trying to do something similar https://github.com/npm/cli/pull/4/files

**Comment by azdanov** [comment]
This looks promising: https://github.com/eslint/eslint/issues/9711

And https://github.com/mysticatea/vue-eslint-demo

**Comment by jorgegonzalez** [comment]
Very interesting
