### ISSUE TITLE
An easier way to communicate

### ISSUE THREAD

**Issue by azdanov** [jorgegonzalez/zoe#30]
Some instant messaging platform: Gitter, Discord or Telegram?

**Comment by jorgegonzalez** [comment]
[Spectrum](https://spectrum.chat/) is also good for questions, so we can have a community there too. https://spectrum.chat/zoe

**Comment by azdanov** [comment]
I've made [`gitter.im/zoe-js`](https://gitter.im/zoe-js).

**Comment by azdanov** [comment]
I think there should be only one place, otherwise it's too saturated. Won't be able to respond to all communication channels.

Which one is more popular?

**Comment by jorgegonzalez** [comment]
Gitter is more popular, let's stick to that.
