### ISSUE TITLE
Add configuration files for development

### ISSUE THREAD

**Issue by azdanov** [jorgegonzalez/zoe#37]
It would be useful to include `.prettierrc`, `.eslintrc` or `tslint.json` for the development. I've stumbled couple of times already by introducing wrong style to the project. And running `zoe` repeatedly is cumbersome.

__Edit:__

Also I've had issues with cryptic error messages which didn't help at all.

For example I've used a type cast in my code `<any>isString` that got picked up as part of JSX syntax, yet the file extension was `.ts`. Only by manually removing parts of code I've managed to find this issue.

**Comment by jorgegonzalez** [comment]
I agree

**Comment by azdanov** [comment]
I've added `.prettierrc` in 8684c2efa1a29ccf1a3321a47eae97f14de2833e and `tslint` in ef11f895f9bbd666d25ae2a4fc73408e1175f429.

**Comment by jorgegonzalez** [comment]
I want to look into the following rulesets, both for our project configuration, as well as for the	 future if/when we decide to add TSLint support to Zoe.

* https://github.com/Microsoft/tslint-microsoft-contrib
* https://github.com/buzinas/tslint-eslint-rules
* https://github.com/ajafff/tslint-consistent-codestyle

**Comment by jorgegonzalez** [comment]
Oh wow these are all included in `tslint-config-airbnb`! Nice!

**Comment by jorgegonzalez** [comment]
A root `.eslintrc` can just extends from `configs/base.json`, in fact I would prefer this.
