### ISSUE TITLE
node_modules is included

### ISSUE THREAD

**Issue by azdanov** [jorgegonzalez/zoe#39]
When running `zoe .` node_modules directory also gets included.

This line is probably responsible for this: https://github.com/jorgegonzalez/zoe/blob/bc526464e77ab7bf34ca67c2c107b4ea2d731e5c/src/engine.ts#L78

And need some way to ignore node_modules by default, since it might be absent in `.gitignore`.

**Comment by azdanov** [comment]
Interesting how [xo](https://github.com/xojs/xo/blob/e7837040a33e83174e6834e64086b95d8d55ecc8/index.js#L92) handles this.

**Comment by jorgegonzalez** [comment]
I think we should assume `zoe` is the same as running `zoe .`?

**Comment by azdanov** [comment]
Yep. But for example if I mistype `zoe ..` it will still glob node_modules. But this time parent's every directory.

Prettier ignores node_modules by default, I wonder how they implemented that.

**Comment by jorgegonzalez** [comment]
XO also ignores node_modules even if you pass it in.

**Comment by jorgegonzalez** [comment]
We're overthinking this. Let's assume a user never wants to lint what is in `.gitignore` plus the default `globbyIgnores`.

**Comment by jorgegonzalez** [comment]
ca5c11dd0133be86cafab1a3223da190d153a10e
