### ISSUE TITLE
Adopt TSLint

### ISSUE THREAD

**Issue by jorgegonzalez** [jorgegonzalez/zoe#41]
I think it would be interesting if we managed to use TSLint (in addition to ESLint) to lint TypeScript files, and then merge the reports. Not sure how difficult that will be yet, I've never used the TSLint API.

**Comment by jorgegonzalez** [comment]
One thing to consider is duplicate errors. Many rules check for the same things yet have different names, and (as far as I know) there's no documented mapping of TSLint -> ESLint rule names. This is probably a good idea for a new module.

**Comment by jorgegonzalez** [comment]
https://github.com/buzinas/tslint-eslint-rules

This is a good mapping. Not sure how complete it is.

**Comment by azdanov** [comment]
What does `eslint-typescript` offer that `tslint` does not have?

**Comment by jorgegonzalez** [comment]
Mostly plugins `eslint-plugin-[node, unicorn, import, no-use-extend-native, promise]`

**Comment by azdanov** [comment]
Disable all non-plugin rules for typescript files?

**Comment by jorgegonzalez** [comment]
Maybe.

**Comment by jorgegonzalez** [comment]
Also, in my opinion, ESLint will eventually overtake TSLint in usage for all JS+TS projects lands native TypeScript support (via [typescript-eslint-parser(https://github.com/eslint/typescript-eslint-parser)).

**Comment by azdanov** [comment]
I agree. ESLint has a richer ecosystem. TSLint is mostly supported by angular developers _(Over generalizing of course)_.

**Comment by jorgegonzalez** [comment]
I think the benefits do not currently outweigh the costs on integrating TSLint. Closing this for now.
