### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by azdanov** [jorgegonzalez/zoe#43]
Would be nice to see what areas area slow. It will certainly help find bottlenecks in zoe.

There are many areas that could slow down an app. Will have to investigate, since I don't have much experience in optimization.

**Comment by jorgegonzalez** [comment]
I know for a fact that the biggest bottlenecks are the `CLIEngine.executeOnFiles()` calls. 

https://github.com/jorgegonzalez/zoe/blob/master/src/engine.ts#L43
https://github.com/jorgegonzalez/zoe/blob/master/src/engine.ts#L53

Can't do much about that, but they might perform better in ESLint v5, which I'm waiting for `eslint-config-airbnb` to upgrade to:

https://github.com/airbnb/javascript/issues/1834#issuecomment-406726653

**Comment by jorgegonzalez** [comment]
`promisify`-ing those calls and running `Promise.all()` could maybe improve things? Not sure.
