### ISSUE TITLE
Create new eslint-formatter

### ISSUE THREAD

**Issue by jorgegonzalez** [jorgegonzalez/zoe#54]
This is what we're using right now: https://github.com/sindresorhus/eslint-formatter-pretty

I think it would be a good idea to make our own.

**Comment by azdanov** [comment]
What would be the end goal? (apart from learning to build something cool)

**Comment by jorgegonzalez** [comment]
It would allow us complete control over how the CLI output looks (i.e. if we wanted to change something, we wouldn't have to wait on someone else to merge a PR), and it would push us further away from XO in style as this is the formatter they use.
