### ISSUE TITLE
JS rules in TypeScript

### ISSUE THREAD

**Issue by texastoland** [jorgegonzalez/zoe#86]
Some JavaScript rules are less relevant:

[`default-case`](https://eslint.org/docs/rules/default-case) (type checked but safer with untyped code)

Or entirely replaced in TypeScript:

`no-useless-constructor` (typescript-eslint/typescript-eslint#334)

Should they be explicitly disabled and commented why?

**Comment by jorgegonzalez** [comment]
Go ahead and turn them off https://github.com/jorgegonzalez/zoe/blob/master/eslint-config-zoe/typescript.js

**Comment by texastoland** [comment]
Cool I'll check which other rules are duplicated by either type checking or `@typescript/eslint` and PR soon!

**Comment by jorgegonzalez** [comment]
Going to assume this is no longer an issue unless it is reopened.

**Comment by texastoland** [comment]
Still an issue; I just never PRed.

**Comment by jorgegonzalez** [comment]
Closed in `zoe@1.31.4`

**Comment by texastoland** [comment]
I couldn't find it in the repo, and your history appears to have been erased. Could you link the relevant commit?

**Comment by jorgegonzalez** [comment]
Sorry, I restarted the project from scratch. This is the latest config https://github.com/jorgegonzalez/eslint-config-zoe/blob/master/index.js
