### ISSUE TITLE
Vue errors not using Vue

### ISSUE THREAD

**Issue by texastoland** [jorgegonzalez/zoe#87]
The most recent release `1.27.0` (strangely missing from GitHub) added Vue and flooded every file with errors like:

```
Use the latest vue-eslint-parser.
See also https://vuejs.github.io/eslint-plugin-vue/user-guide/#what-is-the-use-the-latest-vue-eslint-parser-error
eslint(vue/...)
```

My guess is it doesn't play nice with the TypeScript parser. Maybe it shouldn't be extended by default?

**Comment by jorgegonzalez** [comment]
Yeah need to fix that ...

**Comment by texastoland** [comment]
I don't agree with the linked fix. It basically defers the first parser to the Vue parser. If another plugin were to do that you'd end up with Russian dolls. For now my workaround in `package.json` is:

```json
  "resolutions": {
    "eslint-config-zoe": "1.19.1"
  }
```

**Comment by jorgegonzalez** [comment]
Sorry I mean *I* need to fix this. Will hopefully get it done this weekend.

**Comment by texastoland** [comment]
I knew what you meant 🤗

**Comment by jorgegonzalez** [comment]
Temporarily dropping Vue support.

**Comment by jorgegonzalez** [comment]
Closing this unless someone wants Vue support.
